name: wordleoff-blazor-wasm
static_sites:
- name: wordleoff
  github:
    repo: magicsgram/wordleoff
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.build 
  output_dir: /output/wwwroot
  index_document: index.html
  catchall_document: index.html
